import Head from 'next/head'
import axios from "axios"
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react"
import Checkboxfield from '../components/checkbox';
import Graph from "../components/graph";

function Home() {
  const [prefectures, setPreFectures] = useState<{
    message: null;
    result: {
      prefCode: number;
      prefName: string;
    }[];
  } | null>(null);

  const [prefPopulation, setPrefPopulation] = useState<
    { prefName: string; data: { year: number; value: number }[] }[]
  >([]);

  useEffect(() => {
    axios
      .get("https://opendata.resas-portal.go.jp/api/v1/prefectures", {
        headers: { "X-API-KEY": process.env.API },
      })
      .then((results) => {
        setPreFectures(results.data);
      })
      .catch((error) => {});
  }, []);

  const handleClickCheck = (
    prefName: string,
    prefCode: number,
    check: boolean
  ) => {
    let c_prefPopulation = prefPopulation.slice();
    if (check) {
      if ( c_prefPopulation.findIndex( (value) => value.prefName === prefName) !== -1 )
        return;
        axios.get( "https://opendata.resas-portal.go.jp/api/v1/population/composition/perYear?cityCode=-&prefCode=" + String(prefCode),
          {
            headers: { "X-API-KEY": process.env.API },
          }
        )
        .then((results) => {
          c_prefPopulation.push({
            prefName: prefName,
            data: results.data.result.data[0].data,
          });
          setPrefPopulation(c_prefPopulation);
        })
        .catch((error) => {
          return;
        });
    } else {
      const deleteIndex = c_prefPopulation.findIndex(
        (value) => value.prefName === prefName
      );
      if (deleteIndex === -1) return;
      c_prefPopulation.splice(deleteIndex, 1);
      setPrefPopulation(c_prefPopulation);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>都道府県別の総人口推移グラフ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          都道府県別の総人口推移グラフ
        </h1>
        <div id="Checkboxlist">
          {prefectures && (
          <Checkboxfield
            prefectures={prefectures.result}
            onChange={handleClickCheck}
          />
        )}
        </div>
        <div id="HighchartsReact">
          <Graph populationdata={prefPopulation} />
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  )
}
export default Home;